import { createClient } from '@supabase/supabase-js'

export default createClient('https://lzzjergirprqwtgxyjrd.supabase.co',
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6emplcmdpcnBycXd0Z3h5anJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzExMDY4NzUsImV4cCI6MTk4NjY4Mjg3NX0.0AHmmGCq5yAYRZtT7ADNnZFC1tg0yZYoN5NLgAbSp6g')